services:
  - type: web
    name: telegram-bot
    env: python
    plan: free  # bisa diganti ke starter/hobby sesuai kebutuhan
    buildCommand: pip install -r requirements.txt
    startCommand: python Python.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: RENDER_URL
        value: https://bot-lwq9.onrender.com
